# Generated by Django 4.1.3 on 2023-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_brand_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
